<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>NovaLauncher</AssemblyName>
    <RootNamespace>NovaLauncher</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Platforms>x64</Platforms>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="AppIcon.ico"/>
  </ItemGroup>

</Project>
